require'config'
require'plugins'

require'plugins.gruvbox'
require'plugins.telescope'
require'plugins.luasnip'
require'plugins.cmp'
require'plugins.lsp'
require'plugins.treesitter'
require'plugins.conform'
require'plugins.bufferline'
require'plugins.leap'
require'plugins.vimspector'
require'plugins.vimtex'
require'plugins.tagbar'
require'plugins.gitsigns'
