require'config'
require'plugins.xkbswitch'
require'plugins.vimspector'

require'plugman'

require'plugins.gruvbox'
require'plugins.telescope'
require'plugins.luasnip'
require'plugins.cmp'
require'plugins.lsp'
require'plugins.treesitter'
require'plugins.conform'
require'plugins.lint'
require'plugins.bufferline'
require'plugins.leap'
require'plugins.vimtex'
require'plugins.tagbar'
require'plugins.gitsigns'
